In [1]:
import numpy as np

## (a)

In [2]:
arr = np.random.randint(1, 51, size=(4,5))
arr

array([[22, 35, 20,  2, 19],
       [36,  8, 11, 44, 35],
       [41, 20, 12, 36, 23],
       [ 7, 14, 50, 35,  8]])

## (b)

In [3]:
np.sum(arr)

478

## (c)

In [6]:
index = np.argmax(arr)
row = index // 5
col = index % 4 + 1
print(arr[row, col])

50


## (d)

In [8]:
np.mean(arr)

23.9

## (e)

In [10]:
np.sum(arr, axis=1)

array([ 98, 134, 132, 114])

## (f)

In [11]:
arr.T

array([[22, 36, 41,  7],
       [35,  8, 20, 14],
       [20, 11, 12, 50],
       [ 2, 44, 36, 35],
       [19, 35, 23,  8]])

## (g)

In [12]:
arr > 25

array([[False,  True, False, False, False],
       [ True, False, False,  True,  True],
       [ True, False, False,  True, False],
       [False, False,  True,  True, False]])