In [1]:
import numpy as np

## (a)

In [2]:
arr = np.random.randint(1, 51, size=(4,5))
arr

array([[14, 30, 27, 50, 10],
       [42, 47, 23,  8,  2],
       [32, 47, 28, 20,  9],
       [10, 31, 21,  1, 24]])

## (b)

In [3]:
np.sum(arr)

476

## (c)

In [4]:
np.max(arr)

50

## (d)

In [5]:
np.mean(arr)

23.8

## (e)

In [6]:
np.sum(arr, axis=1)

array([131, 122, 136,  87])

## (f)

In [7]:
arr.T

array([[14, 42, 32, 10],
       [30, 47, 47, 31],
       [27, 23, 28, 21],
       [50,  8, 20,  1],
       [10,  2,  9, 24]])

## (g)

In [8]:
arr > 25

array([[False,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False, False],
       [False,  True, False, False, False]])